### ISSUE TITLE
How to parallel computing multiple image pairs?

### ISSUE THREAD

**Issue by youwyu** [angli66/simsense#2]
May I ask how to parallel compute multiple image pairs? Such as left and right images with shape [N, height, width].

**Comment by angli66** [comment]
Hi, currently I don’t have support for batch computing and supporting this would require some modifications to the source code. However there’s a quick hack I can think of: you can stack all of the images in one direction and add enough zero padding (wider than max disparity level) between every two nearby images so that they won’t interfere with each other.

**Comment by youwyu** [comment]
Thank you for your quick and helpful response. This is an easy but good solution. I have a followup: May I ask how can we generate (simulate) test/left1.png since from the whole code I only found the D415 pattern for test/left2.png. The pattern for test/left.png seems like the D435 pattern.

**Comment by angli66** [comment]
You are right, left1 was taken by a real D435 camera while left2 was simulated with [SAPIEN](https://github.com/haosulab/SAPIEN). If you are interested in simulating D435 pattern, you might want to checkout the dev branch of SAPIEN where we include parameters for D435. An example usage can be found [here](https://github.com/haosulab/SAPIEN/blob/dev/manualtest/stereodepth.py).
